mcdp: assets/test-data/downloaded/lib1-simple.models.drone1.mcdpr1.yaml
query: FixResMaxFun
approximated: true
value:
  mass: '0'
result:
  $schema:
    title: Interval
  pessimistic:
    $schema:
      title: LowerSet
    maximals:
    - - '0'
      - Infinity
      - Infinity
    - - Infinity
      - '0'
      - '0'
  optimistic:
    $schema:
      title: LowerSet
    maximals:
    - - '0'
      - Infinity
      - Infinity
    - - Infinity
      - '0'
      - '0'
