dp: lib1-simple.primitivedps.drone1.mcdpr1.yaml
query: FixFunMinRes
approximated: true
value:
- '20.10000000'
- '3.60000000'
- '46.25'
result:
  $schema:
    title: Interval
  pessimistic:
    $schema:
      title: UpperSet
    minimals:
    - '0.00054433'
  optimistic:
    $schema:
      title: UpperSet
    minimals:
    - '0.00054433'
